---
- hosts: all
  become: true
  tasks:
  - name: install apache2 and php package 
    package: 
      name: # This are variable that can be set in inventory file
        - "{{ apache_package }}"
        - "{{ php_package  }}" 
      state: latest
      update_cache: yes
     

